sudo: required

services:
    - docker

branches:
    only:
        - master

before_install:
    # get last version
    - export VER=$(git describe --tags --abbrev=0)

    # make images
    - docker build -t $DOCKER_USERNAME/apache-tika-server:$VER .

script:
    - echo Apache Tika Server version $VER
    - docker run --name tika -d --rm -p 127.0.0.1:9998:9998 fmantuano/apache-tika-server:$VER
    - docker top tika | grep tika
    - docker stop tika

after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $DOCKER_USERNAME/apache-tika-server:$VER

notifications:
    slack: spamscope:$SLACK_KEY
